### ISSUE TITLE
Optimization_issue

### ISSUE THREAD

**Issue by ale18032005** [chan-csu/ADToolbox#15] opened 2024-10-04 23:15 UTC
Traceback (most recent call last):
  File "..", line 466, in <module>
    print(optimize.calculate_fit_stats(model=model,data=training_data))
  File "...", line 654, in calculate_fit_stats
    x=np.array(x)
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (250,) + inhomogeneous part.

**Comment by ParsaGhadermazi** [comment] 2024-10-11 22:27
Hi Alejandra,

The issue is now fixed. It happened because calculate_fit_stats was designed to work with data that had exactly same shapes. Now this is fixed.

Best,
Parsa

**Closed by ParsaGhadermazi** 2024-10-11 22:27 UTC
